# Disabled cache in hope of improving reliability of AppVeyor builds
cache:
- "c:\\sr" # stack root, short paths == fewer problems

build: off

# before_test:

install:
  # 
  # z3
  # 
- mkdir $HOME/z3 || echo exists
- wget -O z3.zip https://github.com/Z3Prover/z3/releases/download/z3-4.4.1/z3-4.4.1-x64-win.zip
  # https://github.com/Z3Prover/z3/releases/download/z3-4.4.1/z3-4.4.1-x86-win.zip
- unzip z3.zip
- cp z3-4.4.1-x64-win-10.11/bin/z3.exe $HOME/z3.exe
- export PATH="$HOME/z3:$PATH"
- z3 -h
  # 
  # Stack
  # 
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"
  matrix: 
    - lts: --resolver lts-3
    - lts: --resolver lts-6
    - lts: --resolver lts-7
    - lts: ""

platform:
  - x86
  - x64

test_script:
- pwd
- stack setup > nul
# The ugly echo "" hack is to avoid complaints about 0 being an invalid file
# descriptor
- echo "" | stack --no-terminal test
